### ISSUE TITLE
[24.01.07~24.01.12 24:00] 1주차 스터디 문제

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [AlgorithmTa/Hwang#1]
|기간|24.01.07~24.01.12 24:00|
|:---:|:---|
|링크|[Link🔗](https://school.programmers.co.kr/learn/challenges?order=acceptance_desc&page=1&search=2023+KAKAO)|

### TODO
- [x] [개인정보 수집 유효기간](https://school.programmers.co.kr/learn/courses/30/lessons/150370)
- [x] [이모티콘 할인행사](https://school.programmers.co.kr/learn/courses/30/lessons/150368)
- [x] [택배 배달과 수거하기](https://school.programmers.co.kr/learn/courses/30/lessons/150369)
- [x] [미로 탈출 명령어](https://school.programmers.co.kr/learn/courses/30/lessons/150365)
- [x] [표현 가능한 이진트리](https://school.programmers.co.kr/learn/courses/30/lessons/150367)
